#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Create short-lived bootstrap material for one fresh private node.

Required env:
  NODE_NAME            virtual node name, used only for output filename by default
  VCLUSTER_ENDPOINT    host:port that the node will contact

Optional env:
  OUT                  output env file (default: /tmp/vcluster-private-node-${NODE_NAME}.env)
  KUBECONFIG           virtual-cluster kubeconfig path/context source
  KUBEADM_TOKEN_TTL    bootstrap token lifetime, Go duration (default: 24h)
  SA_TOKEN_DURATION    service account token duration (default: 24h)

The output file contains secrets and is chmod 0600. The script prints only the
path and does not print token values.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

: "${NODE_NAME:?set NODE_NAME}"
: "${VCLUSTER_ENDPOINT:?set VCLUSTER_ENDPOINT}"

KUBEADM_TOKEN_TTL="${KUBEADM_TOKEN_TTL:-24h}"
SA_TOKEN_DURATION="${SA_TOKEN_DURATION:-24h}"
OUT="${OUT:-/tmp/vcluster-private-node-${NODE_NAME}.env}"

command -v kubectl >/dev/null 2>&1 || {
  echo "kubectl is required" >&2
  exit 1
}
command -v openssl >/dev/null 2>&1 || {
  echo "openssl is required" >&2
  exit 1
}

token_id="$(openssl rand -hex 16 | cut -c1-6)"
token_secret="$(openssl rand -hex 16 | cut -c1-16)"
kubeadm_token="${token_id}.${token_secret}"
expiration="$(python3 - "${KUBEADM_TOKEN_TTL}" <<'PY'
from datetime import datetime, timedelta, timezone
import re
import sys

duration = sys.argv[1]
match = re.fullmatch(r"(\d+)([smhd])", duration)
if not match:
    raise SystemExit(f"unsupported KUBEADM_TOKEN_TTL {duration!r}; use a simple duration like 24h")
value = int(match.group(1))
unit = match.group(2)
delta = {
    "s": timedelta(seconds=value),
    "m": timedelta(minutes=value),
    "h": timedelta(hours=value),
    "d": timedelta(days=value),
}[unit]
print((datetime.now(timezone.utc) + delta).strftime("%Y-%m-%dT%H:%M:%SZ"))
PY
)"

kubectl apply -f - >/dev/null <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: bootstrap-token-${token_id}
  namespace: kube-system
type: bootstrap.kubernetes.io/token
stringData:
  token-id: ${token_id}
  token-secret: ${token_secret}
  usage-bootstrap-authentication: "true"
  usage-bootstrap-signing: "true"
  auth-extra-groups: system:bootstrappers:kubeadm:default-node-token
  expiration: ${expiration}
EOF

kube_proxy_token="$(kubectl -n kube-system create token kube-proxy --duration "${SA_TOKEN_DURATION}")"
konnectivity_token="$(kubectl -n kube-system create token konnectivity-agent --audience system:konnectivity-server --duration "${SA_TOKEN_DURATION}")"
ca_b64="$(kubectl config view --raw --minify -o jsonpath='{.clusters[0].cluster.certificate-authority-data}')"
if [[ -z "${ca_b64}" ]]; then
  ca_file="$(kubectl config view --raw --minify -o jsonpath='{.clusters[0].cluster.certificate-authority}')"
  if [[ -z "${ca_file}" ]]; then
    echo "could not find certificate authority data in current kubeconfig" >&2
    exit 1
  fi
  ca_b64="$(base64 -w0 <"${ca_file}")"
fi

umask 077
mkdir -p "$(dirname -- "$OUT")"
cat >"$OUT" <<EOF
# Generated by scripts/mint-node-secrets.sh. Do not commit or paste publicly.
NODE_NAME='${NODE_NAME}'
VCLUSTER_ENDPOINT='${VCLUSTER_ENDPOINT}'
VCLUSTER_CA_B64='${ca_b64}'
KUBEADM_TOKEN='${kubeadm_token}'
KUBE_PROXY_TOKEN='${kube_proxy_token}'
KONNECTIVITY_TOKEN='${konnectivity_token}'
EOF
chmod 0600 "$OUT"

echo "Wrote secret node env file: ${OUT}"
echo "Delete the bootstrap token after use if it is no longer needed: kubectl -n kube-system delete secret bootstrap-token-${token_id}"
